### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by marahim20** [ad-si/invoice-maker#16]
Update the readme to support the location of the example files now.

**Comment by marahim20** [comment]
I love your project. It has helped me a lot. I'm happy to help with this issue.

**Comment by ad-si** [comment]
Thanks for the nice words and the the heads up! 😊
Fixed it in 87efa40!

**Comment by ad-si** [comment]
> I'm happy to help with this issue.

There is something else I could use some help @marahim20! Maybe check out the PR to publish it as a package (https://github.com/typst/packages/pull/466) and leave a comment there about your thoughts! =)

**Comment by marahim20** [comment]
Ok. I'll check it out.
